// <auto-generated />
using System;
using Journey.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Journey.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220524122510_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Journey.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaceName")
                        .IsUnique();

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 5, 24, 15, 25, 10, 749, DateTimeKind.Local).AddTicks(9475),
                            Description = "Ut atque eius nobis.",
                            PlaceName = "Apartment on Kamyanetskaya street",
                            UpdatedAt = new DateTime(2022, 5, 24, 15, 25, 10, 749, DateTimeKind.Local).AddTicks(9505)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(136),
                            Description = "Et quos est dolor quisquam et sit iure consectetur fugit.",
                            PlaceName = "Avto Spa",
                            UpdatedAt = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(140)
                        });
                });

            modelBuilder.Entity("Journey.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArrived")
                        .HasColumnType("bit");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalDate = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1021),
                            CreatedAt = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1015),
                            DepartureDate = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1023),
                            IsArrived = false,
                            PlaceId = 1,
                            UpdatedAt = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1020)
                        },
                        new
                        {
                            Id = 2,
                            ArrivalDate = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1028),
                            CreatedAt = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1025),
                            DepartureDate = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1029),
                            IsArrived = false,
                            PlaceId = 1,
                            UpdatedAt = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1026)
                        },
                        new
                        {
                            Id = 3,
                            ArrivalDate = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1065),
                            CreatedAt = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1061),
                            DepartureDate = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1066),
                            IsArrived = false,
                            PlaceId = 2,
                            UpdatedAt = new DateTime(2022, 5, 24, 15, 25, 10, 750, DateTimeKind.Local).AddTicks(1063)
                        });
                });

            modelBuilder.Entity("Journey.Entities.Reservation", b =>
                {
                    b.HasOne("Journey.Entities.Place", "Place")
                        .WithMany("Reservations")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Journey.Entities.Place", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
